const locationData = [
    {
      S_N: 1,
      city: 'Sharjah',
      area: 'All Sharjah areas',
      route_description: 'Route1',
      plate_no: 52869,
      vehicle_code: '00235',
      type: 'LIGHT',
      area_1: 'All Areas',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 63576,
      vehicle_vode_2: '00195',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 10423,
      vehicle_code_3: '00076',
      type_3: 'HEAVY',
      area_1_3: 'All Areas'
    },
    {
      S_N: 2,
      city: 'Sharjah',
      area: 'All Sharjah areas',
      route_description: 'Route1',
      plate_no: 82492,
      vehicle_code: '0062',
      type: 'LIGHT',
      area_1: 'All Areas',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 67030,
      vehicle_vode_2: '00463',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 52873,
      vehicle_code_3: '00034',
      type_3: 'HEAVY',
      area_1_3: 'All Areas'
    },
    {
      S_N: 3,
      city: 'Sharjah',
      area: 'All Sharjah areas',
      route_description: 'Route1',
      plate_no: 31607,
      vehicle_code: '00156',
      type: 'LIGHT',
      area_1: 'All Areas',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 67031,
      vehicle_vode_2: '00369',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 4,
      city: 'Sharjah',
      area: 'All Sharjah areas',
      route_description: 'Route1',
      plate_no: 31680,
      vehicle_code: '00105',
      type: 'LIGHT',
      area_1: 'All Areas',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 68949,
      vehicle_vode_2: '00525',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 5,
      city: 'Sharjah',
      area: 'All Sharjah areas',
      route_description: 'Route1',
      plate_no: 91002,
      vehicle_code: '0087',
      type: 'LIGHT',
      area_1: 'All Areas',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 82350,
      vehicle_vode_2: '00306',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 6,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 83560,
      vehicle_vode_2: '00365',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 7,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 85183,
      vehicle_vode_2: '00194',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 8,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 93295,
      vehicle_vode_2: '00310',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 9,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 98604,
      vehicle_vode_2: '00310',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 10,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 17109,
      vehicle_vode_2: '00368',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 11,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 26481,
      vehicle_vode_2: '00172',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 12,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 40825,
      vehicle_vode_2: '00309',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 13,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 45807,
      vehicle_vode_2: '00461',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 14,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 48160,
      vehicle_vode_2: '00350',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 15,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 52873,
      vehicle_vode_2: '00034',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 16,
      city: 'Sharjah',
      route_description: 'Route1',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 53667,
      vehicle_vode_2: '00366',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 17,
      city: 'DUBAI',
      area: 'NAD AL SHIBA, SILICON, DUBAI LAND,',
      route_description: 'Route2',
      plate_no: 13927,
      vehicle_code: '00312',
      type: 'LIGHT',
      area_1: 'Nad Al Shiba',
      area_2: 'Silicon',
      area_3: 'Dubai Land',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 34358,
      vehicle_vode_2: '00163',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 52873,
      vehicle_code_3: '00034',
      type_3: 'HEAVY',
      area_1_3: 'All Areas'
    },
    {
      S_N: 18,
      city: 'DUBAI',
      area: 'DEIRA SOUQ, HOR AL ANZ.MAMZAR,PORT SAEED.RIGG, MURAKKABAT,NAIF ROAD,AL MATEENA STREET ,MANAMA STREET , ABU HAIL,,HAMRIYA PORT',
      route_description: 'Route3',
      plate_no: 19613,
      vehicle_code: '00176',
      type: 'LIGHT',
      area_1: 'Deira Souq',
      area_2: 'Hor Al Anz',
      area_3: 'Mamzar',
      area_4: 'Port Saeed',
      area_5: 'Rigga',
      area_6: 'Murakkabat',
      area_7: 'Naif Road',
      area_8: 'Al Mateena Street',
      area_9: 'Manama Street',
      area_10: 'Abu Hail',
      area_11: 'Hamriya Port',
      plate_no_2: 48160,
      vehicle_vode_2: '00350',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 10423,
      vehicle_code_3: '00076',
      type_3: 'HEAVY',
      area_1_3: 'All Areas'
    },
    {
      S_N: 19,
      city: 'DUBAI',
      area: 'AL QOUZ,1 AND 2',
      route_description: 'Route4',
      plate_no: 26481,
      vehicle_code: '00172',
      type: 'LIGHT',
      area_1: 'Al Qouz 1',
      area_2: 'Al Qouz 2',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 39861,
      vehicle_vode_2: '00351',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 28368,
      vehicle_code_3: '00077',
      type_3: 'HEAVY',
      area_1_3: 'All Areas'
    },
    {
      S_N: 20,
      city: 'DUBAI',
      area: 'RASHIDIYA , UMM AL RAMOOL ,AL WARQA ,CREEK, NAD AL HAMMER, MIRDIF',
      route_description: 'Route5',
      plate_no: 34358,
      vehicle_code: '00367',
      type: 'LIGHT',
      area_1: 'Rashidiya',
      area_2: 'Umm Al Ramool',
      area_3: 'Al Warqa',
      area_4: 'Creek',
      area_5: 'Nad Al Hammer',
      area_6: 'Mirdif',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 45807,
      vehicle_vode_2: '00461',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 52861,
      vehicle_code_3: '00236',
      type_3: 'HEAVY',
      area_1_3: 'All Areas'
    },
    {
      S_N: 21,
      city: 'DUBAI',
      area: 'RAS AL KHOR, INT,CITY, WARSAN, WADI AL SHABAK, AWEER VILLAGE',
      route_description: 'Route6',
      plate_no: 48161,
      vehicle_code: '00231',
      type: 'LIGHT',
      area_1: 'Ras Al Khor',
      area_2: 'Int City',
      area_3: 'Warsan',
      area_4: 'Wadi Al Shabak',
      area_5: 'Aweer Village',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 68949,
      vehicle_vode_2: '00525',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 77219,
      vehicle_code_3: '00058',
      type_3: 'HEAVY',
      area_1_3: 'All Areas'
    },
    {
      S_N: 22,
      city: 'DUBAI',
      area: 'BUR , KARAMA, SATWA, JADAF, WAFI CITY, UDD AL METAH',
      route_description: 'Route7',
      plate_no: 48176,
      vehicle_code: '00224',
      type: 'LIGHT',
      area_1: 'Bur',
      area_2: 'Karama',
      area_3: 'Satwa',
      area_4: 'Jadaf',
      area_5: 'Wafi City',
      area_6: 'Udd Al Metah',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 31735,
      vehicle_vode_2: '00526',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 23,
      city: 'DUBAI',
      area: ' HILL , ARABIAN RANCHES,MAYDAN, UMM AL NAHDA',
      route_description: 'Route8',
      plate_no: 74680,
      vehicle_code: '00233',
      type: 'LIGHT',
      area_1: 'Hill',
      area_2: 'Arabian Ranches',
      area_3: 'Maydan',
      area_4: 'Umm Al Nahda',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 57644,
      vehicle_vode_2: '00364',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 24,
      city: 'DUBAI',
      area: 'QUSAISES,SUNAPOOR,MAMZAR, KHAWANEEJ,AL NAHDA,MUHAISNAH',
      route_description: 'Route9',
      plate_no: 85183,
      vehicle_code: '00194',
      type: 'LIGHT',
      area_1: 'Qusaises',
      area_2: 'Sunapoor',
      area_3: 'Mamzar',
      area_4: 'Khawaneej',
      area_5: 'Al Nahda',
      area_6: 'Muhaisnah',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 93295,
      vehicle_vode_2: '00310',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 25,
      city: 'DUBAI',
      area: 'AL QOUZ,3 AND 4 UMM SUQEIM SOUTH AL BARSHA AL BARSHA 1',
      route_description: 'Route10',
      plate_no: 87069,
      vehicle_code: '00193',
      type: 'LIGHT',
      area_1: 'Al Qouz 3',
      area_2: 'Al Qouz 4',
      area_3: 'Umm Suqeim',
      area_4: 'South Al Barsha',
      area_5: 'Al Barsha 1',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 63576,
      vehicle_vode_2: '00195',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 26,
      city: 'DUBAI',
      area: 'INVESTMENT PARK,1,2 DWC,MAKTOOM AIRPORT AL QUDRA,AKOYA OXYGEN',
      route_description: 'Route11',
      plate_no: 89115,
      vehicle_code: '00232',
      type: 'LIGHT',
      area_1: 'Investment Park 1',
      area_2: 'Investment Park 2',
      area_3: 'Dwc',
      area_4: 'Maktoom Airport',
      area_5: 'Al Qudra',
      area_6: 'Akoya Oxygen',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 60231,
      vehicle_vode_2: '00311',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 27,
      city: 'DUBAI',
      area: 'AFZA, JEBEL ALI IND AREA,FURJAN,IBN BATTUTA,TECHNO PARK,DISCOVERY GARDEN, JEBEL ALI HILLS',
      route_description: 'Route12',
      plate_no: 93985,
      vehicle_code: '00197',
      type: 'LIGHT',
      area_1: 'Afza',
      area_2: 'Jebel Ali Ind Area',
      area_3: 'Furjan',
      area_4: 'Ibn Battuta',
      area_5: 'Techno Park',
      area_6: 'Discovery Garden',
      area_7: 'Jebel Ali',
      area_8: 'Hills',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 67030,
      vehicle_vode_2: '00463',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 28,
      city: 'DUBAI',
      area: 'JVC,AL BARSHA, MARINA.BUSINESS BAY,',
      route_description: 'Route13',
      plate_no: 92370,
      vehicle_code: '00088',
      type: 'LIGHT',
      area_1: 'Jvc',
      area_2: 'Al Barsha',
      area_3: 'Marina',
      area_4: 'Business Bay',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 98604,
      vehicle_vode_2: '00306',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 29,
      city: 'DUBAI',
      route_description: 'Route14',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 43577,
      vehicle_vode_2: '00352',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 30,
      city: 'DUBAI',
      route_description: 'Route14',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 67031,
      vehicle_vode_2: '00369',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 31,
      city: 'DUBAI',
      route_description: 'Route14',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 53667,
      vehicle_vode_2: '00366',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 32,
      city: 'DUBAI',
      route_description: 'Route14',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 40825,
      vehicle_vode_2: '00309',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 33,
      city: 'DUBAI',
      route_description: 'Route14',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 39647,
      vehicle_vode_2: '00348',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 34,
      city: 'DUBAI',
      route_description: 'Route14',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 70125,
      vehicle_vode_2: '00349',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 35,
      city: 'DUBAI',
      route_description: 'Route14',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 83560,
      vehicle_vode_2: '00365',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 36,
      city: 'DUBAI',
      route_description: 'Route14',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 98604,
      vehicle_vode_2: '00306',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 37,
      city: 'AlAin',
      area: 'AL AIN SHOWROOM AL JAHILY, MAZYAD',
      route_description: 'Route15',
      plate_no: 31735,
      vehicle_code: '00526',
      type: 'LIGHT',
      area_1: 'Al Ain Showroom',
      area_2: 'Al Jahily',
      area_3: 'Mazyad',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 13927,
      vehicle_vode_2: '00312',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 52873,
      vehicle_code_3: '00034',
      type_3: 'HEAVY',
      area_1_3: 'MAZYAD'
    },
    {
      S_N: 41,
      city: 'AlAin',
      area: 'AL AIN ,AL YAHAR, HILLY INDUSTRIAL AREA,AL HAYER, AL LASILY,AL RIMAH,BARARY,BATEEN , MURKHANIA',
      route_description: 'Route16',
      plate_no: 48160,
      vehicle_code: '00350',
      type: 'LIGHT',
      area_1: 'Al Yahar',
      area_2: 'Hilly Industrial Area',
      area_3: 'Al Hayer',
      area_4: 'Al Lasily',
      area_5: 'Al Rimah',
      area_6: 'Barary',
      area_7: 'Bateen',
      area_8: 'Murkhania',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 48161,
      vehicle_vode_2: '00231',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 77219,
      vehicle_code_3: '00058',
      type_3: 'HEAVY',
      area_1_3: 'MAZYAD'
    },
    {
      S_N: 39,
      city: 'AlAin',
      area: 'AL AIN ,MAZYAD, ZAHER, UMM UL GHAFA,AL JIMI, NEW TRUCK ROAD',
      route_description: 'Route17',
      plate_no: 39861,
      vehicle_code: '00351',
      type: 'LIGHT',
      area_1: 'Mazyad',
      area_2: 'Zaher',
      area_3: 'Umm Ul Ghafa',
      area_4: 'Al Jimi',
      area_5: 'New Truck Road',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 26481,
      vehicle_vode_2: '00172',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 28368,
      vehicle_code_3: '00077',
      type_3: 'HEAVY',
      area_1_3: 'MAZYAD'
    },
    {
      S_N: 40,
      city: 'AlAin',
      area: 'INDUSTRIAL AREA',
      route_description: 'Route18',
      plate_no: 45807,
      vehicle_code: '00461',
      type: 'LIGHT',
      area_1: 'Industrial Area',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 34358,
      vehicle_vode_2: '00367',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 52861,
      vehicle_code_3: '00236',
      type_3: 'HEAVY',
      area_1_3: 'MAZYAD'
    },
    {
      S_N: 42,
      city: 'AlAin',
      area: 'AL AIN INDUSTRIAL AREA',
      route_description: 'Route18',
      plate_no: 57644,
      vehicle_code: '00364',
      type: 'LIGHT',
      area_1: 'Industrial Area',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 48176,
      vehicle_vode_2: '00224',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 82097,
      vehicle_code_3: '00060',
      type_3: 'HEAVY',
      area_1_3: 'MAZYAD'
    },
    {
      S_N: 43,
      city: 'AlAin',
      area: 'INDUSTRIAL AREA',
      route_description: 'Route18',
      plate_no: 68949,
      vehicle_code: '00525',
      type: 'LIGHT',
      area_1: 'Industrial Area',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 74680,
      vehicle_vode_2: '00233',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 44,
      city: 'AlAin',
      area: 'INDUSTRIAL AREA',
      route_description: 'Route18',
      plate_no: 93295,
      vehicle_code: '00310',
      type: 'LIGHT',
      area_1: 'Industrial Area',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 85183,
      vehicle_vode_2: '00194',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 45,
      city: 'AlAin',
      route_description: 'Route19',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 87069,
      vehicle_vode_2: '00193',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 46,
      city: 'AlAin',
      route_description: 'Route19',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 89115,
      vehicle_vode_2: '00232',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 47,
      city: 'AlAin',
      route_description: 'Route19',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 93985,
      vehicle_vode_2: '00197',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 48,
      city: 'AlAin',
      route_description: 'Route19',
      area_1: '',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 92370,
      vehicle_vode_2: '00088',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    },
    {
      S_N: 49,
      city: 'FUJAIRAH',
      area: 'KHORFAKKAN,MURRABAH .BEDIYA,DADNA.GARRIYA',
      route_description: 'Route20',
      plate_no: 63576,
      vehicle_code: '00195',
      type: 'LIGHT',
      area_1: 'Khorfakkan',
      area_2: 'Murrabah',
      area_3: 'Bediya',
      area_4: 'Dadna',
      area_5: 'Garriya',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 40825,
      vehicle_vode_2: '00309',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 13927,
      vehicle_code_3: '00312',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 50,
      city: 'FUJAIRAH',
      area: 'PORT, MASAFI,AL HAIL,,THOBAN',
      route_description: 'Route21',
      plate_no: 60231,
      vehicle_code: '00311',
      type: 'LIGHT',
      area_1: 'Port',
      area_2: 'Masafi',
      area_3: 'Al Hail',
      area_4: 'Thoban',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 39647,
      vehicle_vode_2: '00348',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 26481,
      vehicle_code_3: '00172',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 51,
      city: 'FUJAIRAH',
      area: 'DIBBA, HALA.,DIBBA AL HOSAN',
      route_description: 'Route22',
      plate_no: 67030,
      vehicle_code: '00463',
      type: 'LIGHT',
      area_1: 'Dibba',
      area_2: 'Hala',
      area_3: 'Dibba Al Hosan',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 83560,
      vehicle_vode_2: '00365',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 87069,
      vehicle_code_3: '00193',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 52,
      city: 'FUJAIRAH',
      area: 'KALBA, AL SAAF INDUSTRIAL AREA, KOR KALBA',
      route_description: 'Route23',
      plate_no: 43577,
      vehicle_code: '00352',
      type: 'LIGHT',
      area_1: 'Kalba',
      area_2: 'Al Saaf Industrial Area',
      area_3: 'Kor Kalba',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 98604,
      vehicle_vode_2: '00306',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 89115,
      vehicle_code_3: '00232',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 53,
      city: 'FUJAIRAH',
      area: 'MANAMA ,AL SHOWKA , AL GHAIL. ADEN',
      route_description: 'Route24',
      plate_no: 67031,
      vehicle_code: '00369',
      type: 'LIGHT',
      area_1: 'Manama',
      area_2: 'Al Showka',
      area_3: 'Al Ghail. Aden',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 82350,
      vehicle_vode_2: '00306',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 93985,
      vehicle_code_3: '00197',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 54,
      city: 'FUJAIRAH',
      area: 'AL DHAID,AL GHAIL',
      route_description: 'Route25',
      plate_no: 53667,
      vehicle_code: '00366',
      type: 'LIGHT',
      area_1: 'Al Dhaid',
      area_2: 'Al Ghail',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: ''
    },
    {
      S_N: 55,
      city: 'AJMAN',
      area: 'INDUSTRIAL AREA , HAMRIYA FREE ZONE, HELLO, JURF,',
      route_description: 'Route26',
      plate_no: 49611,
      vehicle_code: '00125',
      type: 'LIGHT',
      area_1: 'Industrial Area',
      area_2: 'Hamriya Free Zone',
      area_3: 'Hello',
      area_4: 'Jurf',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 63576,
      vehicle_vode_2: '00195',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 93985,
      vehicle_code_3: '00197',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 57,
      city: 'AJMAN',
      area: 'INDUSTRIAL AREA , HAMRIYA FREE ZONE, HELLO, JURF,',
      route_description: 'Route26',
      plate_no: '58437',
      vehicle_code: '00129',
      type: 'LIGHT',
      area_1: 'Industrial Area',
      area_2: 'Hamriya Free Zone',
      area_3: 'Hello',
      area_4: 'Jurf',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 67030,
      vehicle_vode_2: '00463',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 26481,
      vehicle_code_3: '00172',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 56,
      city: 'AJMAN',
      area: 'IND.AREA ,MUSHARRAF,RASHIDIYA, NAEMIYA ,RAWADA',
      route_description: 'Route27',
      plate_no: 69288,
      vehicle_code: '00196',
      type: 'LIGHT',
      area_1: 'Industrial Area',
      area_2: 'Musharraf',
      area_3: 'Rashidiya',
      area_4: 'Naemiya',
      area_5: 'Rawada',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 60231,
      vehicle_vode_2: '00311',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 13927,
      vehicle_code_3: '00312',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 58,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 43577,
      vehicle_vode_2: '00352',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 74680,
      vehicle_code_3: '00233',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 59,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 67031,
      vehicle_vode_2: '00369',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 85183,
      vehicle_code_3: '00194',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 60,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 53667,
      vehicle_vode_2: '00366',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 87069,
      vehicle_code_3: '00193',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 61,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 31735,
      vehicle_vode_2: '00526',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 89115,
      vehicle_code_3: '00232',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 62,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 34358,
      vehicle_vode_2: '00163',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 63,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 39861,
      vehicle_vode_2: '00351',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 64,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 45807,
      vehicle_vode_2: '00461',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 65,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 48160,
      vehicle_vode_2: '00350',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 66,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 57644,
      vehicle_vode_2: '00364',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 67,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 68949,
      vehicle_vode_2: '00525',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 68,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 93295,
      vehicle_vode_2: '00310',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 69,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 40825,
      vehicle_vode_2: '00309',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 70,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 39647,
      vehicle_vode_2: '00348',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 71,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 70125,
      vehicle_vode_2: '00349',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 72,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 83560,
      vehicle_vode_2: '00365',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 73,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 98604,
      vehicle_vode_2: '00306',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 74,
      city: 'AJMAN',
      route_description: 'Route28',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 82350,
      vehicle_vode_2: '00306',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      area_1_3: 'All Areas'
    },
    {
      S_N: 75,
      city: 'RAK',
      area: 'RIFFA AL DHAITH ,JAZEERA AL HAMRAH,KHARAN',
      route_description: 'Route29',
      plate_no: 40825,
      vehicle_code: '00309',
      type: 'LIGHT',
      area_1: 'Riffa Al Dhaith',
      area_2: 'Jazeera Al Hamrah',
      area_3: 'Kharan',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 63576,
      vehicle_vode_2: '00195',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 52869,
      vehicle_code_3: '00235',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 79,
      city: 'RAK',
      area: 'RIFFA AL DHAITH ,JAZEERA AL HAMRAH,KHARAN',
      route_description: 'Route29',
      plate_no: 98604,
      vehicle_code: '00306',
      type: 'LIGHT',
      area_1: 'Riffa Al Dhaith',
      area_2: 'Jazeera Al Hamrah',
      area_3: 'Kharan',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 67031,
      vehicle_vode_2: '00369',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 91002,
      vehicle_code_3: '0087',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 80,
      city: 'RAK',
      area: 'RIFFA AL DHAITH ,JAZEERA AL HAMRAH,KHARAN',
      route_description: 'Route29',
      plate_no: 82350,
      vehicle_code: '00306',
      type: 'LIGHT',
      area_1: 'Riffa Al Dhaith',
      area_2: 'Jazeera Al Hamrah',
      area_3: 'Kharan',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 53667,
      vehicle_vode_2: '00366',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 13927,
      vehicle_code_3: '00312',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 76,
      city: 'RAK',
      area: 'NAKHEEL, HUZAM, BURAIRAT',
      route_description: 'Route30',
      plate_no: 39647,
      vehicle_code: '00348',
      type: 'LIGHT',
      area_1: 'Nakheel',
      area_2: 'Huzam',
      area_3: 'Burairat',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 60231,
      vehicle_vode_2: '00311',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 82492,
      vehicle_code_3: '0062',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 77,
      city: 'RAK',
      area: 'SHAM ,RAMS .JULAN, SHAMAL KHURKHOR',
      route_description: 'Route31',
      plate_no: 70125,
      vehicle_code: '00349',
      type: 'LIGHT',
      area_1: 'Sham',
      area_2: 'Rams .Julan',
      area_3: 'Shamal Khurkhor',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 67030,
      vehicle_vode_2: '00463',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 31607,
      vehicle_code_3: '00156',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 78,
      city: 'RAK',
      area: 'QUSAIDAT',
      route_description: 'Route32',
      plate_no: 83560,
      vehicle_code: '00365',
      type: 'LIGHT',
      area_1: 'Qusaidat',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 43577,
      vehicle_vode_2: '00352',
      type_2: 'LIGHT',
      area_1_2: 'All Areas',
      plate_no_3: 31680,
      vehicle_code_3: '00105',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 81,
      city: 'RAK',
      route_description: 'Route33',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_3: 26481,
      vehicle_code_3: '00172',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 82,
      city: 'RAK',
      route_description: 'Route33',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_3: 87069,
      vehicle_code_3: '00193',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 83,
      city: 'RAK',
      route_description: 'Route33',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_3: 89115,
      vehicle_code_3: '00232',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 84,
      city: 'RAK',
      route_description: 'Route33',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_3: 93985,
      vehicle_code_3: '00197',
      type_3: 'LIGHT',
      area_1_3: 'All Areas'
    },
    {
      S_N: 85,
      city: 'Abu Dhabi',
      area: 'Al-Mussafah',
      route_description: 'Route34',
      plate_no: 16846,
      vehicle_code: '00462',
      type: 'LIGHT',
      area_1: 'Al-Mussafah',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 52873,
      vehicle_vode_2: '00034',
      type_2: 'HEAVY',
      area_1_2: 'Al-Mussafah',
      plate_no_3: 45807,
      vehicle_code_3: '00461',
      type_3: 'LIGHT',
      area_1_3: 'Al-Mussafah'
    },
    {
      S_N: 86,
      city: 'Abu Dhabi',
      area: 'Al-Mussafah',
      route_description: 'Route34',
      plate_no: 82097,
      vehicle_code: '00060',
      type: 'HEAVY',
      area_1: 'Al-Mussafah',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 10423,
      vehicle_vode_2: '00076',
      type_2: 'HEAVY',
      area_1_2: 'Al-Mussafah',
      plate_no_3: 68949,
      vehicle_code_3: '00525',
      type_3: 'LIGHT',
      area_1_3: 'Al-Mussafah'
    },
    {
      S_N: 87,
      city: 'Abu Dhabi',
      route_description: 'Route35',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 28368,
      vehicle_vode_2: '00077',
      type_2: 'HEAVY',
      plate_no_3: 40825,
      vehicle_code_3: '00309',
      type_3: 'LIGHT',
      area_1_3: 'Al-Mussafah'
    },
    {
      S_N: 88,
      city: 'Abu Dhabi',
      route_description: 'Route35',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 52861,
      vehicle_vode_2: '00236',
      type_2: 'HEAVY',
      plate_no_3: 82350,
      vehicle_code_3: '00306',
      type_3: 'LIGHT',
      area_1_3: 'Al-Mussafah'
    },
    {
      S_N: 89,
      city: 'Abu Dhabi',
      route_description: 'Route35',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 77219,
      vehicle_vode_2: '00058',
      type_2: 'HEAVY',
      plate_no_3: 87069,
      vehicle_code_3: '00193',
      type_3: 'LIGHT',
      area_1_3: 'Al-Mussafah'
    },
    {
      S_N: 90,
      city: 'Abu Dhabi',
      route_description: 'Route35',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_3: '52227',
      vehicle_code_3: '00128',
      type_3: 'LIGHT',
      area_1_3: 'Al-Mussafah'
    },
    {
      S_N: 91,
      city: 'UMM AL QUIN',
      area: 'UMM AL QUIN,\r\n' +
        'NEW INDUSTRIAL AREA OLD IND AREA,. SALMA. SOUQ,MATAFI. RAFFAH, AL KABIR,',
      route_description: 'Route36',
      plate_no: 17109,
      vehicle_code: '00368',
      type: 'LIGHT',
      area_1: 'All Areas',
      area_2: '',
      area_3: '',
      area_4: '',
      area_5: '',
      area_6: '',
      area_7: '',
      area_8: '',
      area_9: '',
      area_10: '',
      area_11: '',
      plate_no_2: 53667,
      vehicle_vode_2: '00366',
      type_2: 'LIGHT',
      area_1_2: 'All Areas'
    }
  ]

export default locationData;